PedList = {
    {
        name = "MAN PEDS",
        categoriesImage = "./assets/img/categories/manpeds.png",
        peds = {
            "A_M_M_ARMCHOLERACORPSE_01",
            "A_M_M_ARMTOWNFOLK_01",
            "A_M_M_ARMTOWNFOLK_02",
            "A_M_M_ASBMINER_01",
            "A_M_M_ASBMINER_02",
            "A_M_M_ASBMINER_03",
            "A_M_M_ASBMINER_04",
            "A_M_M_ASBTOWNFOLK_01",
            "A_M_M_ASBTOWNFOLK_01_LABORER",
            "A_M_M_BIVWORKER_01",
            "A_M_M_BIWTOWNFOLK_01",
            "A_M_M_BIWUPPERCLASS_01",
            "A_M_M_BLWOBESEMEN_01",
            "A_M_M_BTCOBESEMEN_01",
            "A_M_M_GUATOWNFOLK_01",
            "A_M_M_LAGTOWNFOLK_01",
            "A_M_M_LOWERSDTOWNFOLK_01",
            "A_M_M_LOWERSDTOWNFOLK_02",
            "A_M_M_MIDDLESDTOWNFOLK_01",
            "A_M_M_MIDDLESDTOWNFOLK_02",
            "A_M_M_MIDDLESDTOWNFOLK_03",
            "A_M_M_NBXDOCKWORKERS_01",
            "A_M_M_NBXUPPERCLASS_01",
            "A_M_M_RANCHER_01",
            "A_M_M_RHDDEPUTYRESIDENT_01",
            "A_M_M_RHDOBESEMEN_01",
            "A_M_M_RHDTOWNFOLK_01",
            "A_M_M_RHDTOWNFOLK_01_LABORER",
            "A_M_M_RHDTOWNFOLK_02",
            "A_M_M_RHDUPPERCLASS_01",
            "A_M_M_SDCHINATOWN_01",
            "A_M_M_SDDOCKWORKERS_02",
            "A_M_M_SKPPRISONER_01",
            "A_M_M_SKPPRISONLINE_01",
            "A_M_M_STRDEPUTYRESIDENT_01",
            "A_M_M_STRTOWNFOLK_01",
            "A_M_M_TUMTOWNFOLK_01",
            "A_M_M_TUMTOWNFOLK_02",
            "A_M_M_UNICORPSE_01",
            "A_M_M_UPPERTRAINPASSENGERS_01",
            "A_M_M_VALTOWNFOLK_01",
            "A_M_M_VALTOWNFOLK_02",
            "A_M_M_VHTTOWNFOLK_01",
            "A_M_M_WAPWARRIORS_01",
            "A_M_O_BIWUPPERCLASS_01",
            "A_M_O_GUATOWNFOLK_01",
            "A_M_O_LAGTOWNFOLK_01",
            "A_M_O_SDCHINATOWN_01",
            "A_M_O_SDUPPERCLASS_01",
            "A_M_O_WAPTOWNFOLK_01",
            "A_M_Y_ASBMINER_01",
            "A_M_Y_ASBMINER_02",
            "A_M_Y_ASBMINER_03",
            "A_M_Y_ASBMINER_04",
            "A_M_Y_UNICORPSE_01",
            "U_M_M_APFDEADMAN_01",
            "U_M_M_ARMGENERALSTOREOWNER_01",
            "U_M_M_ARMTRAINSTATIONWORKER_01",
            "U_M_M_BIVFOREMAN_01",
            "U_M_M_BHT_BANDITOMINE",
            "U_M_M_BHT_BANDITOSHACK",
            "U_M_M_BHT_BLACKWATERHUNT",
            "U_M_M_BHT_ODRISCOLLDRUNK",
            "U_M_M_BHT_ODRISCOLLMAULED",
            "U_M_M_BHT_OUTLAWMAULED",
            "U_M_M_BHT_SKINNERSEARCH",
            "U_M_M_BIWTRAINSTATIONWORKER_01",
            "U_M_M_CAJHOMESTAD_01",
            "U_M_M_CHELONIANJUMPER_01",
            "U_M_M_CHELONIANJUMPER_02",
            "U_M_M_CHELONIANJUMPER_03",
            "U_M_M_CHELONIANJUMPER_04",
            "U_M_M_CIRCUSWAGON_01",
            "U_M_M_CRDHOMESTEADTENANT_01",
            "U_M_M_CRDHOMESTEADTENANT_02",
            "U_M_M_CREOLECAPTAIN_01",
            "U_M_M_CZPHOMESTEADFARHER_01",
            "U_M_M_CZPHOMESTEADFATHER_01",
            "U_M_M_DORHOMESTEADHUSBAND_01",
            "U_M_M_EMRFARMHAND_03",
            "U_M_M_FINALE2_AA_UPPERCLASS_01",
            "U_M_M_GALASTRINGQUARTET_01",
            "U_M_M_GALASTRINGQUARTET_02",
            "U_M_M_GALASTRINGQUARTET_03",
            "U_M_M_GALASTRINGQUARTET_04",
            "U_M_M_HHRRANCHER_01",
            "U_M_M_HTLRANCHERBOUNTY_01",
            "U_M_M_LNSWORKER_01",
            "U_M_M_LNSWORKER_02",
            "U_M_M_LNSWORKER_03",
            "U_M_M_LNSWORKER_04",
            "U_M_M_LRSHOMESTEADTENANT_01",
            "U_M_M_MFRRANCHER_01",
            "U_M_M_NBXBARTENDER_01",
            "U_M_M_NBXBARTENDER_02",
            "U_M_M_NBXGENERALSTOREOWNER_01",
            "U_M_M_NBXLIVERYWORKER_01",
            "U_M_M_NBXPRIEST_01",
            "U_M_M_RHDBACKUPDEPUTY_01",
            "U_M_M_RHDBACKUPDEPUTY_02",
            "U_M_M_RHDBARTENDER_01",
            "U_M_M_RHDDOCTOR_01",
            "U_M_M_RHDFIDDLEPLAYER_01",
            "U_M_M_RHDSHERIFF_01",
            "U_M_M_RHDTRAINSTATIONWORKER_01",
            "U_M_M_RKFRANCHER_01",
            "U_M_M_RWFRANCHER_01",
            "U_M_M_SDBANKGUARD_01",
            "U_M_M_SDEXOTICSSHOPKEEPER_01",
            "U_M_M_SDPHOTOGRAPHER_01",
            "U_M_M_SDPOLICECHIEF_01",
            "U_M_M_SHACKSERIALKILLER_01",
            "U_M_M_STORY_PIGFARM_01",
            "U_M_M_STRSHERIFF_01",
            "U_M_M_TUMBARTENDER_01",
            "U_M_M_TUMBUTCHER_01",
            "U_M_M_TUMTRAINSTATIONWORKER_01",
            "U_M_M_UNIBOUNTYHUNTER_02",
            "U_M_M_UNIBOUNTYHUNTER_01",
            "U_M_M_VALBARBER_01",
            "U_M_M_VALBARTENDER_01",
            "U_M_M_VALBUTCHER_01",
            "U_M_M_VALDOCTOR_01",
            "U_M_M_VALSHERIFF_01",
            "U_M_M_VALTOWNFOLK_01",
            "U_M_M_VALTOWNFOLK_02",
            "U_M_M_VHTSTATIONCLERK_01",
            "U_M_M_WALGENERALSTOREOWNER_01",
            "U_M_M_WTCCOWBOY_04",
            "U_M_O_ARMBARTENDER_01",
            "U_M_O_ASBSHERIFF_01",
            "U_M_O_BIWGENERALSTOREOWNER_01",
            "U_M_O_BLWBARTENDER_01",
            "U_M_O_BLWPHOTOGRAPHER_01",
            "U_M_O_BLWPOLICECHIEF_01",
            "U_M_O_CAJHOMESTEAD_01",
            "U_M_O_CMRCIVILWARCOMMANDO_01",
            "U_M_O_MAPWISEOLDMAN_01",
            "U_M_O_PSHRANCHER_01",
            "U_M_O_RIGTRAINSTATIONWORKER_01",
            "U_M_O_VALBARTENDER_01",
            "U_M_O_VHTEXOTICSHOPKEEPER_01",
            "U_M_Y_CAJHOMESTEAD_01",
            "U_M_Y_CZPHOMESTEADSON_01",
            "U_M_Y_CZPHOMESTEADSON_02",
            "U_M_Y_CZPHOMESTEADSON_03",
            "U_M_Y_CZPHOMESTEADSON_04",
            "U_M_Y_CZPHOMESTEADSON_05",
            "U_M_Y_HTLWORKER_01",
            "U_M_Y_HTLWORKER_02",
            "G_M_M_BOUNTYHUNTERS_01",
            "G_M_M_UNIDUSTER_03",
            "G_M_M_UNILNBRED_01",
            "G_M_M_UNIMOUNTAINMEN_01",
            "G_M_M_UNIRANCHERS_01",
            "G_M_M_UNISWAMP_01",
            "G_M_Y_UNIEXCONFEDS_02",
            "RE_SAVAGEWAGON_MALES_01",
            "RE_SAVAGEWARNING_MALES_01",
            "RE_STALKINGHUNTER_MALES_01",
            "RE_TOWNBURIAL_MALES_01",
            "RE_SAVAGEAFTERMATH_MALES_01",
            "RE_LONEPRISONER_MALES_01",
            "RE_LOSTFRIEND_MALES_01",
            "RE_MURDERCAMP_MALES_01",
            "RE_PLAYERCAMPSTRANGERS_MALES_01",
            "RE_POLICECHASE_MALES_01",
            "RE_PRISONWAGON_MALES_01",
            "RE_RALLYDISPUTE_MALES_01",
            "RE_RALLYSETUP_MALES_01",
            "RE_RALLY_MALES_01",
            "RE_FROZENDEATH_MALES_01",
            "MSP_GANG3_MALES_01",
            "MSP_INDUSTRY3_MALES_01",
            "MSP_TRAINROBBERY2_MALES_01",
            "RCSP_CALLOWAY_MALES_01",
            "RCSP_DUTCH1_MALES_01",
            "RCSP_FORMYART_MALES_01",
            "RE_BOATATTACK_MALES_01",
            "RE_DEADBODIES_MALES_01",
            "MES_SADIE4_MALES_01",
            "MP_ASN_BRAITHWAITEMANOR_MALES_03",
            "S_M_M_AMBIENTBLWPOLICE_01",
            "S_M_M_AMBIENTLAWRURAL_01",
            "S_M_M_AMBIENTSDPOLICE_01",
            "S_M_M_ARMY_01",
            "S_M_M_BARBER_01",
            "S_M_M_BWMWORKER_01",
            "S_M_M_CGHWORKER_01",
            "S_M_M_CKTWORKER_01",
            "S_M_M_DISPATCHLAWRURAL_01",
            "S_M_M_DISPATCHLEADERPOLICE_01",
            "S_M_M_DISPATCHPOLICE_01",
            "S_M_M_LIVERYWORKER_01",
            "S_M_M_MAPWORKER_01",
            "S_M_M_MARKETVENDOR_01",
            "S_M_M_RACRAILWORKER_01",
            "S_M_M_SKPGUARD_01",
            "S_M_M_STGSAILOR_01",
            "S_M_M_TAILOR_01",
            "S_M_M_TRAINSTATIONWORKER_01",
            "S_M_M_TUMDEPUTIES_01",
            "S_M_M_UNIBUTCHERS_01",
            "S_M_M_VALDEPUTY_01",
            "S_M_O_CKTWORKER_01",
            "S_M_Y_ARMY_01",
            "S_M_Y_NEWSPAPERBOY_01",
            "S_M_Y_RACRAILWORKER_01",
        }
    },
    {
        name = "WOMEN PEDS",
        categoriesImage = "./assets/img/categories/womenpeds.png",
        peds = {
            "A_F_M_ARMCHOLERACORPSE_01",
            "A_F_M_ARMTOWNFOLK_01",
            "A_F_M_ARMTOWNFOLK_02",
            "A_F_M_ASBTOWNFOLK_01",
            "A_F_M_BIWTOWNFOLK_01",
            "A_F_M_BIWTOWNFOLK_02",
            "A_F_M_BIWUPPERCLASS_01",
            "A_F_M_BTCOBESEWOMEN_01",
            "A_F_M_GUATOWNFOLK_01",
            "A_F_M_LAGTOWNFOLK_01",
            "A_F_M_LOWERSDTOWNFOLK_01",
            "A_F_M_LOWERSDTOWNFOLK_02",
            "A_F_M_LOWERSDTOWNFOLK_03",
            "A_F_M_MIDDLESDTOWNFOLK_01",
            "A_F_M_MIDDLESDTOWNFOLK_02",
            "A_F_M_MIDDLESDTOWNFOLK_03",
            "A_F_M_NBXUPPERCLASS_01",
            "A_F_M_RDHTOWNFOLK_02",
            "A_F_M_RHDTOWNFOLK_01",
            "A_F_M_RHDUPPERCLASS_01",
            "A_F_M_SDCHINATOWN_01",
            "A_F_M_SKPPRISONONLINE_01",
            "A_F_M_STRTOWNFOLK_01",
            "A_F_M_TUMTOWNFOLK_01",
            "A_F_M_TUMTOWNFOLK_02",
            "A_F_M_UNICORPSE_01",
            "A_F_M_UPPERTRAINPASSENGERS_01",
            "A_F_M_VALTOWNFOLK_01",
            "A_F_M_VHTTOWNFOLK_01",
            "A_F_M_WAPTOWNFOLK_01",
            "A_F_O_BIWUPPERCLASS_01",
            "A_F_O_GUATOWNFOLK_01",
            "A_F_O_LAGTOWNFOLK_01",
            "A_F_O_SDCHINATOWN_01",
            "A_F_O_SDUPPERCLASS_01",
            "A_F_O_WAPTOWNFOLK_01",
            "U_F_M_CIRCUSWAGON_01",
            "U_F_M_EMRDAUGHTER_01",
            "U_F_M_TLJBARTENDER_01",
            "U_F_M_TUMGENERALSTOREOWNER_01",
            "U_F_M_VALTOWNFOLK_01",
            "U_F_M_VALTOWNFOLK_02",
            "U_F_M_VHTBARTENDER_01",
            "U_F_O_HERMIT_WOMAN_01",
            "U_F_O_WTCTOWNFOLK_01",
            "U_F_Y_BRAITWAITESSECRET_01",
            "MBH_RHODESRACHER_FEMALES_01",
            "MP_ASN_SDWEDDING_FEMALES_01",
            "MSP_BOUNTYHUNTER1_FEMALES_01",
            "RE_DEADJOHN_FEMALES_01",
            "RE_FROZENTODEATH_FEMALES_01",
            "RE_SAVAGEAFTERMATH_FEMALES_01",
            "RE_SAVAGEWAGON_FEMALES_01",
            "RE_TOWNWIDOW_FEMALES_01",
            "RE_VOICE_FEMALES_01",
            "S_F_M_BWMWORKER_01",
            "S_F_M_CGHWORKER_01",
            "S_F_M_MAPWORKER_01",
        }
    },
    {
        name = "SPECIAL PEDS",
        categoriesImage = "./assets/img/categories/specialpeds.png",
        peds = {
            "CS_ABIGAILROBERTS",
            "CS_ACROBAT",
            "CS_ASBDEPUTY_01",
            "CS_BAPTISTE",
            "CS_BLWPHOTOGRAPHER",
            "CS_BROTHERDORKINS",
            "CS_CAPTAINMONROE",
            "CS_CHAINPRISONER_01",
            "CS_CHAINPRISONER_02",
            "CS_CHELONIANMASTER",
            "CS_COLFAVOURS",
            "CS_COLMODRISCOLL",
            "CS_CORNWALLTRAINCONDUCTOR",
            "CS_CRACKPOTROBOT",
            "CS_CREOLEDOCTOR",
            "CS_DUNCANGEDDES",
            "CS_DUTCH",
            "CS_EAGLEFLIES",
            "CS_EVELYNMILLER",
            "CS_GERMANDAUGHTER",
            "CS_GERMANSON",
            "CS_HESTONJAMESON",
            "CS_JACKMARSTON",
            "CS_JACKMARSTON_TEEN",
            "CS_JAMIE",
            "CS_JOHNTHEBAPTISINGMADMAN",
            "CS_JOHNWEATHERS",
            "CS_LONDONDERRYSON",
            "CS_MAGNIFICO",
            "CS_MARSHALL_THURWELL",
            "CS_MEDITATINGMONK",
            "CS_MICAHBELL",
            "CS_MILTONANDREWS",
            "CS_MP_BOUNTYHUNTER",
            "CS_MP_JORGE_MONTEZ",
            "CS_MP_MARSHALL_DAVIES",
            "CS_MP_SHERIFFFREEMAN",
            "CS_MP_TEDDYBROWN",
            "CS_NBXPOLICECHIEFFORMAL",
            "CS_ODPROSTITUTE",
            "CS_PRIEST_WEDDING",
            "CS_RAINSFALL",
            "CS_RHODEPUTY_01",
            "CS_RHODEPUTY_02",
            "CS_RINGMASTER",
            "CS_SDDOCTOR_01",
            "CS_SHERIFFOWENS",
            "CS_SISTERCALDERON",
            "CS_STRDEPUTY_01",
            "CS_STRDEPUTY_02",
            "CS_STRSHERIFF_01",
            "CS_SWAMPFREAK",
            "CS_VALDEPUTY_01",
            "CS_VALSHERIFF",
            "CS_VAMPIRE",
            "CS_WAPITIBOY",
            "CS_WATSON_02",
            "CS_TILLY",
            "MP_PREDATOR",
            "MP_G_F_M_ARMYOFFEAR_01",
            "MP_G_M_M_ARMYOFFEAR_01",
            "MBH_RHODESRANCHER_TEENS_01",
        }
    },
    {
        name = "KID PEDS",
        categoriesImage = "./assets/img/categories/kidpeds.png",
        peds = {
            "a_m_y_nbxstreetkids_01",
            "a_m_y_nbxstreetkids_slums_01",
            "a_m_y_sdstreetkids_slums_02",
            "cs_mixedracekid",
            "cs_rhodeskidnapvictim",
            "cs_sd_streetkid_01",
            "cs_sd_streetkid_01a",
            "cs_sd_streetkid_01b",
            "cs_sd_streetkid_02",
            "cs_sdstreetkidthief",
            "u_m_y_shackstarvingkid_01",
        }
    },
    {
        name = "ANIMAL PEDS",
        categoriesImage = "./assets/img/categories/animalpeds.png",
        peds = {
            "A_C_Alligator_01",
            "MP_A_C_Alligator_01",
            "A_C_Alligator_02",
            "A_C_Badger_01",
            "A_C_Bear_01",
            "A_C_BearBlack_01",
            "MP_A_C_Bear_01",
            "A_C_Beaver_01",
            "MP_A_C_Beaver_01",
            "A_C_Cougar_01",
            "A_C_Panther_01",
            "MP_A_C_Cougar_01",
            "MP_A_C_Panther_01",
            "A_C_Coyote_01",
            "MP_A_C_Coyote_01",
            "A_C_DogAmericanFoxhound_01",
            "A_C_DogBluetickCoonhound_01",
            "A_C_DogCatahoulaCur_01",
            "A_C_DogChesBayRetriever_01",
            "A_C_DogCollie_01",
            "A_C_DogHobo_01",
            "A_C_DogHound_01",
            "A_C_DogHusky_01",
            "A_C_DogLab_01",
            "A_C_DogLion_01",
            "A_C_DogPoodle_01",
            "A_C_DogRufus_01",
            "A_C_DogStreet_01",
            "MP_A_C_DogAmericanFoxhound_01",
            "A_C_Muskrat_01",
            "A_C_Raccoon_01",
            "A_C_Wolf",
            "MP_A_C_Wolf_01",
            "A_C_LionMangy_01",
            "A_C_Wolf_Medium",
            "A_C_Wolf_Small",
            "A_C_Eagle_01",
            "A_C_Duck_01",
            "A_C_Owl_01",
            "A_C_Parrot_01",
            "A_C_Raven_01",
            "A_C_Horse_Arabian_Black",
            "A_C_Deer_01",
            "A_C_Snake_01", 
        }
    },
}

AttackAnimal = {
    {
        models = {
            `A_C_SharkTiger`,
            `A_C_SharkHammerhead_01`
        },
        animation = {
            dict = "creatures_reptile@alligator@melee@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 2.0,
        damage = 75
    },
    {
        models = {
            `A_C_Alligator_01`,
            `MP_A_C_Alligator_01`
        },
        animation = {
            dict = "creatures_reptile@alligator@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_Alligator_02`
        },
        animation = {
            dict = "amb_creatures_reptile@gator_giant@nip_attack",
            name = "nip"
        },
        radius = 3.0,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_Badger_01`
        },
        animation = {
            dict = "creatures_mammal@badger@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Bear_01`,
            `A_C_BearBlack_01`,
            `MP_A_C_Bear_01`
        },
        animation = {
            dict = "creatures_mammal@bear@melee@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 5.0,
        damage = 30
    },
    {
        models = {
            `A_C_Beaver_01`,
            `MP_A_C_Beaver_01`
        },
        animation = {
            dict = "creatures_mammal@beaver@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Cougar_01`,
            `A_C_Panther_01`,
            `MP_A_C_Cougar_01`,
            `MP_A_C_Panther_01`
        },
        animation = {
            dict = "creatures_mammal@cougar@melee@streamed_core",
            name = "attack"
        },
        radius = 2.0,
        force = 3.0,
        damage = 20
    },
    {
        models = {
            `A_C_Coyote_01`,
            `MP_A_C_Coyote_01`
        },
        animation = {
            dict = "creatures_mammal@coyote@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_DogAmericanFoxhound_01`,
            `A_C_DogAustralianShepherd_01`,
            `A_C_DogBluetickCoonhound_01`,
            `A_C_DogCatahoulaCur_01`,
            `A_C_DogChesBayRetriever_01`,
            `A_C_DogCollie_01`,
            `A_C_DogHobo_01`,
            `A_C_DogHound_01`,
            `A_C_DogHusky_01`,
            `A_C_DogLab_01`,
            `A_C_DogLion_01`,
            `A_C_DogPoodle_01`,
            `A_C_DogRufus_01`,
            `A_C_DogStreet_01`,
            `MP_A_C_DogAmericanFoxhound_01`
        },
        animation = {
            dict = "creatures_mammal@dog_pers@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 20
    },
    {
        models = {
            `A_C_Muskrat_01`
        },
        animation = {
            dict = "creatures_mammal@muskrat@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Raccoon_01`
        },
        animation = {
            dict = "creatures_mammal@raccoon@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Wolf`,
            `MP_A_C_Wolf_01`,
            `A_C_LionMangy_01`
        },
        animation = {
            dict = "creatures_mammal@wolf@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 30
    },
    {
        models = {
            `A_C_Wolf_Medium`
        },
        animation = {
            dict = "creatures_mammal@wolf_medium@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 25
    },
    {
        models = {
            `A_C_Wolf_Small`
        },
        animation = {
            dict = "creatures_mammal@wolf_small@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 20
    }
}